FROM node:20-alpine
WORKDIR /usr/src/app

# Remove unused downloaded list
RUN rm -rf /var/lib/apt/lists/*


COPY ./package.json ./yarn.lock ./

RUN yarn

ENV DOCKERIZE_VERSION v0.7.0
RUN apk update --no-cache \
  && apk add --no-cache wget openssl \
  && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
  && apk del wget

EXPOSE 3333

ENV BUILDKIT_PROGRESS=plain

ENTRYPOINT dockerize -timeout 10s -wait tcp://vavatips-api-mongodb:27017 && yarn dev
