from node:16.20.1-bullseye
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*
RUN git config --global --add safe.directory /usr/src/app

COPY ./package.json ./yarn.lock ./

RUN yarn



