### Success example
POST http://localhost:3333/generate_code HTTP/1.1
content-type: application/json

{
  "securityCode":"SECURITY_CODE"
}

#### Invalid token example

POST http://localhost:3333/generate_code HTTP/1.1
content-type: application/json

{
  "securityCode":"INVALID TOKEN"
}

#### Invalid token example

POST http://localhost:3333/generate_code HTTP/1.1
content-type: application/json

{
}

#### Invalid with extra values

POST http://localhost:3333/generate_code HTTP/1.1
content-type: application/json

{
    "securityCode":"SECURITY_CODE",
    "EXTRA_ITEM":""
}
