### get alls posts
GET http://localhost:3333/posts HTTP/1.1

### get maps

GET http://localhost:3333/maps HTTP/1.1

### get agents by map

GET http://localhost:3333/agents/Bind HTTP/1.1


### get posts by agents and map
GET http://localhost:3333/posts/Bind/Sova HTTP/1.1


### create post

POST http://localhost:3333/post HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY4MzA0MzExY2Q1MTg5NzRhMWUxIiwiaWF0IjoxNzA3ODY3MTYxLCJleHAiOjE3MDgzMjc5NjF9.0tkYD5l4i2qdhebGwK2ZiGlaASdMW_-aeRh17LFy5Ao
content-type: application/json

{
  "title":"item",
  "description":"example",
  "tags":{
    "moment": "AfterPlant",
    "difficult": "Example",
    "ability": "Examnple",
    "side": "Left",
    "map": "Ascent",
    "mapPosition": "Examnokle",
    "agent": "Aget"
  },
  "imgs":[
    {
      "_id":"example",
      "description":"descImage",
      "image":"link"
    }
  ]
}

### get a post

GET http://localhost:3333/post/65cbfd33487b6367886303b7 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY4MzA0MzExY2Q1MTg5NzRhMWUxIiwiaWF0IjoxNzA3ODY3MTYxLCJleHAiOjE3MDgzMjc5NjF9.0tkYD5l4i2qdhebGwK2ZiGlaASdMW_-aeRh17LFy5Ao
content-type: application/json

### update post

PUT http://localhost:3333/post/65cbfd33487b6367886303b7 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY4MzA0MzExY2Q1MTg5NzRhMWUxIiwiaWF0IjoxNzA3ODY3MTYxLCJleHAiOjE3MDgzMjc5NjF9.0tkYD5l4i2qdhebGwK2ZiGlaASdMW_-aeRh17LFy5Ao
content-type: application/json

{
  "title":"itemx",
  "description":"example2",
  "tags":{
    "moment": "AfterPlant2",
    "difficult": "Example2",
    "ability": "Examnple2",
    "side": "Left2",
    "map": "Ascent2",
    "mapPosition": "Examnokle2",
    "agent": "Aget2"
  },
  "imgs":[
    {
      "_id":"example2222",
      "description":"desc2",
      "image":"image2"
    }
  ]
}

###  delete post

DELETE http://localhost:3333/post/6161a2fdce40a7938c9cecc0 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IngyIiwibmFtZSI6IngyIiwiaWQiOiI2NWNjMDM1YmYwNjE1OWJmNTgyZTlmN2YiLCJpYXQiOjE3MDc4NjkwMjQsImV4cCI6MTcwODMyOTgyNH0.nI05jGQZsv05HTZLw508oNijEZn2zN4g4ZDhBnnEOho


