
### injection example
POST http://localhost:3333/suggestion?$12 HTTP/1.1
content-type: application/json

{
  "post_id":"23",
  "email": { "$gt": "x" },
  "description":".$extra$_"
}



#### create suggestion

POST http://localhost:3333/suggestion HTTP/1.1
content-type: application/json

{
  "post_id":"61590639cd9902fad4021cc5",
  "email": "example email",
  "description":"example description"
}

#### get suggestion

GET http://localhost:3333/suggestions HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmI4MjgxN2EzZWI2MmRhYTUxOGU1IiwiaWF0IjoxNzA3ODUwMDI0LCJleHAiOjE3MDgzMTA4MjR9.QT_QPHAQb_Al82CpJA-h7XK9DG6YLX_nMt7fNXjcAZE


#### edit suggestion

PUT http://localhost:3333/suggestion/65cbb940a0101e700b394321 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmI4MjgxN2EzZWI2MmRhYTUxOGU1IiwiaWF0IjoxNzA3ODUwMDI0LCJleHAiOjE3MDgzMTA4MjR9.QT_QPHAQb_Al82CpJA-h7XK9DG6YLX_nMt7fNXjcAZE
content-type: application/json

{
  "status":"rejected"
}


#### delete suggestion

DELETE http://localhost:3333/suggestion/65cbbdd32ff1e14abc0f86a3 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmI4MjgxN2EzZWI2MmRhYTUxOGU1IiwiaWF0IjoxNzA3ODUwMDI0LCJleHAiOjE3MDgzMTA4MjR9.QT_QPHAQb_Al82CpJA-h7XK9DG6YLX_nMt7fNXjcAZE

