#### create user

POST http://localhost:3333/user HTTP/1.1
content-type: application/json

{
  "username":"greg",
  "password":"greg",
  "code": "dda21e66-6bcd-481b-8106-aa9932d5cfe8"
}

#### should make auth

POST http://localhost:3333/auth HTTP/1.1
content-type: application/json

{
  "username":"greg",
  "password":"greg"
}


## userLoadFile
#### get user

GET http://localhost:3333/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY2MzVlZDllODY2ODlhNjkwMjI1IiwiaWF0IjoxNzA3ODY1NjYyLCJleHAiOjE3MDgzMjY0NjJ9.9WdyAMsJn3WXA3Sng-YffX3mDiTIXFgpYSi_GiaaU6k


#### update user

PATCH  http://localhost:3333/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY2MzVlZDllODY2ODlhNjkwMjI1IiwiaWF0IjoxNzA3ODY1NjYyLCJleHAiOjE3MDgzMjY0NjJ9.9WdyAMsJn3WXA3Sng-YffX3mDiTIXFgpYSi_GiaaU6k
content-type: application/json

{
  "username":"greg2",
  "password":"ssssssssssssss",
  "image":"omage example"
}


#### update user

DELETE  http://localhost:3333/user HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImdyZWciLCJuYW1lIjoiZ3JlZyIsImlkIjoiNjVjYmY3NjJkY2RiNTc5Nzg0MWQ2NDM4IiwiaWF0IjoxNzA3ODY1OTYwLCJleHAiOjE3MDgzMjY3NjB9.FUUDSKUG8hH3gXR26muKzeUiW6YB_VI8FzkmM0519Ms

