#### create user

POST http://0.0.0.0:3333/user HTTP/1.1
content-type: application/json

{
  "username":"ademir",
  "password":"ademir",
  "code": "<code>"
}

#### make auth

POST http://0.0.0.0:3333/auth HTTP/1.1
content-type: application/json

{
  "username":"developer",
  "password":"developer"
}


#### userLoadFile

#### get this

GET http://0.0.0.0:3333/user HTTP/1.1
Authorization: <jwt>


#### update this

PATCH  http://0.0.0.0:3333/user HTTP/1.1
Authorization: <jwt>
content-type: application/json

{
  "username":"ademir2",
  "password":"ademir2",
  "image":"https://image-ademir.com/image.jpg"
}


#### delte this

DELETE  http://0.0.0.0:3333/user HTTP/1.1
Authorization: <jwt>

