export enum ErrorEnum {
  'RESOURCE_NOT_EXISTS' = 'RESOURCE_NOT_EXISTS',
  'PASSWORD_IS_INVALID' = 'PASSWORD_IS_INVALID',
  'INVALID_PAYLOAD' = 'INVALID_PAYLOAD',
  'NOT_POSSIBLE_GET_IP' = 'NOT_POSSIBLE_GET_IP',
  'TOKEN_IS_INVALID_OR_EXPIRED' = 'TOKEN_IS_INVALID_OR_EXPIRED',
}
