export type CodeErrors =
  | 'USERNAME_ALREADY_EXISTS'
  | 'POST_NOT_EXISTS'
  | 'NO_CAN_DELETE_POST_ANOTHER_USER'
  | 'INVALID_PASSWORD'
  | 'CODE_NOT_FOUND'
  | 'USER_NOT_FOUND'
  | 'USER_ID_NOT_FOUND'
  | 'SUGGESTION_NOT_FOUND'
  | 'INTERNAL_ERROR';
