@baseUrl = http://localhost:3333

### @name addView

POST {{baseUrl}}/agents HTTP/1.1
content-type: application/json

{
  "name":"Other",
  "image":"example"
}


### @name getView

GET {{baseUrl}}/agents HTTP/1.1

