@baseUrl = http://localhost:3333

### @name createMap

POST {{baseUrl}}/maps HTTP/1.1
content-type: application/json

{
  "name":"Other",
  "image":"example"
}


### @name updateMap

POST {{baseUrl}}/maps HTTP/1.1
content-type: application/json

{
  "name":"Other",
  "image":"example"
}



### @name getView

GET {{baseUrl}}/maps HTTP/1.1

