### get alls posts
GET http://localhost:3333/posts HTTP/1.1

### get maps

GET http://localhost:3333/posts/maps HTTP/1.1

### get agents by map

GET http://localhost:3333/posts/agents/Bind HTTP/1.1


### get posts by agents and map
GET http://localhost:3333/posts/Bind/Sova HTTP/1.1


### create post

POST http://localhost:3333/posts HTTP/1.1
Authorization: <jwt>
content-type: application/json

{
  "title":"item",
  "description":"example",
  "tags":{
    "moment": "AfterPlant",
    "difficult": "Example",
    "ability": "Examnple",
    "side": "Left",
    "map": "Ascent",
    "mapPosition": "Examnokle",
    "agent": "Aget"
  },
  "imgs":[
    {
      "id":"example",
      "description":"descImage",
      "image":"link"
    }
  ]
}

### get a post

GET http://localhost:3333/posts/<postId> HTTP/1.1
Authorization: <jwt>
content-type: application/json

### update post

PUT http://localhost:3333/posts/<postId> HTTP/1.1
Authorization: <jwt>
content-type: application/json

{
  "title":"itemx",
  "description":"example2",
  "tags":{
    "moment": "AfterPlant2",
    "difficult": "Example2",
    "ability": "Examnple2",
    "side": "Left2",
    "map": "Ascent2",
    "mapPosition": "Examnokle2",
    "agent": "Aget2"
  },
  "imgs":[
    {
      "id":"example2222",
      "description":"desc2",
      "image":"image2"
    }
  ]
}

###  delete post

DELETE http://localhost:3333/posts/<postId> HTTP/1.1
Authorization: <jwt>


