@baseUrl = http://localhost:3333
@bearerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZW1pciIsIm5hbWUiOiJhZGVtaXIiLCJpZCI6IjE2MzhmMmE5LTM0MWItNDgwOC1iZmVhLTU5ZWQ5MzZhYmZlZSIsImlhdCI6MTcyOTQzNjE2MSwiZXhwIjoxNzI5ODk2OTYxfQ.qJJKLGW0AN2BWtevdYWUDBefUU7xJSqxAQqx05NZDRY
@suggestionIdExample = b22fc246-ffea-44c7-b712-524cb0e36ee6


### @name CreateSuggestion

POST {{baseUrl}}/suggestions HTTP/1.1
content-type: application/json

{
  "postId":"61590639cd9902fad4021cc5",
  "email": "example email",
  "description":"example description"
}

### @name GetSuggestions

GET {{baseUrl}}/suggestions HTTP/1.1
Authorization: {{bearerToken}}


### @name UpdateSuggestion


PUT {{baseUrl}}/suggestions/{{suggestionIdExample}}/ HTTP/1.1
Authorization: {{bearerToken}}
content-type: application/json

{
  "status":"rejected"
}


### @name DeleteSuggestion

DELETE {{baseUrl}}/suggestions/{{suggestionIdExample}} HTTP/1.1
Authorization: {{bearerToken}}

