@bearerToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZW1pciIsIm5hbWUiOiJhZGVtaXIiLCJpZCI6IjE2MzhmMmE5LTM0MWItNDgwOC1iZmVhLTU5ZWQ5MzZhYmZlZSIsImlhdCI6MTcyOTQzOTgxMiwiZXhwIjoxNzI5OTAwNjEyfQ.t-sOPv_D7X_3X8Sw4QYon1twIudg5WNm5SDPdl98sdI
@baseUrl = http://localhost:3333
@tokenCode = 1e68b7ae-3717-4e23-aa57-d50563369b42

### @name createUser

POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
  "username":"ademir",
  "password":"ademir",
  "code": "{{tokenCode}}"
}

### @name uploadFile

### @name getMe

GET {{baseUrl}}/users/me HTTP/1.1
Authorization: {{bearerToken}}


### @name updateUser

PATCH  {{baseUrl}}/users HTTP/1.1
Authorization: {{bearerToken}}
content-type: application/json

{
  "username":"ademir2",
  "password":"ademir2",
  "image":"https://image-ademir.com/image.jpg"
}


### @name deleteThis

DELETE  {{baseUrl}}/users HTTP/1.1
Authorization: {{bearerToken}}

