#### create user

POST http://0.0.0.0:3333/users HTTP/1.1
content-type: application/json

{
  "username":"ademir",
  "password":"ademir",
  "code": "6907ec05-5938-4677-8b2d-d67526d11587"
}

#### make auth

POST http://0.0.0.0:3333/auth HTTP/1.1
content-type: application/json

{
  "username":"developer",
  "password":"developer"
}


#### userLoadFile

#### get this

GET http://0.0.0.0:3333/users/me HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZW1pciIsIm5hbWUiOiJhZGVtaXIiLCJpZCI6IjY3MGZhOGU2OGRmZDhmOTdlMTI4ZjBkYiIsImlhdCI6MTcyOTA3OTczNywiZXhwIjoxNzI5NTQwNTM3fQ.S9aog86wK-qk4jwgqBCfd_qWoNTmE4zAo6a3Flr7XtA


#### update this

PATCH  http://0.0.0.0:3333/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZW1pciIsIm5hbWUiOiJhZGVtaXIiLCJpZCI6IjY3MGZhOGU2OGRmZDhmOTdlMTI4ZjBkYiIsImlhdCI6MTcyOTA3OTczNywiZXhwIjoxNzI5NTQwNTM3fQ.S9aog86wK-qk4jwgqBCfd_qWoNTmE4zAo6a3Flr7XtA
content-type: application/json

{
  "username":"ademir2",
  "password":"ademir2",
  "image":"https://image-ademir.com/image.jpg"
}


#### delte this

DELETE  http://0.0.0.0:3333/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZW1pciIsIm5hbWUiOiJhZGVtaXIiLCJpZCI6IjY3MGZhOGU2OGRmZDhmOTdlMTI4ZjBkYiIsImlhdCI6MTcyOTA3OTczNywiZXhwIjoxNzI5NTQwNTM3fQ.S9aog86wK-qk4jwgqBCfd_qWoNTmE4zAo6a3Flr7XtA

